version: "3.9"

services:
  api:
    image: ghcr.io/edouarddeiber/playnow-api:latest
    container_name: playnow-api
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${EXPRESS_PORT}
      - MONGO_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/${MONGODB_DB_NAME}?authSource=admin
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: playnow-mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mongo_data: