version: "3.9"

services:
  api:
    image: ghcr.io/edouarddeiber/playnow-api:latest
    container_name: playnow-api
    #network_mode: host
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27020/playnow
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: playnow-mongo
    #network_mode: host
    ports:
      - "27020:27020"
    environment:
      - MONGO_INITDB_DATABASE=playnow
    command: ["mongod", "--port", "27020"]
    restart: unless-stopped

volumes:
  mongo_data:
