version: "3.9"

services:
  api:
    image: ghcr.io/edouarddeiber/playnow-api:latest
    container_name: playnow-api
    network_mode: host
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: playnow-mongo
    network_mode: host
    command: ["mongod", "--port", "27020"]
    restart: unless-stopped

volumes:
  mongo_data:
