services:
  api:
    image: ghcr.io/edouarddeiber/playnow-api:latest
    container_name: playnow-api-prod
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=${EXPRESS_PORT}
      - MONGO_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@127.0.0.1:${MONGODB_PORT}/${MONGODB_DB_NAME}?authSource=admin
    env_file:
      - .env.prod
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: mongo-playnow-prod
    network_mode: "host"
    command: ["mongod", "--port", "${MONGODB_PORT}", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_playnow_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --port ${MONGODB_PORT} --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mongo_playnow_data:
