services:
  api:
    build: .
    image: api-playnow-prod
    container_name: playnow-api-prod
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${EXPRESS_PORT}
      # Construction de l'URL Mongo avec authentification
      - MONGO_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/${MONGODB_DB_NAME}?authSource=admin
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8
    container_name: mongo-prod
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data_prod:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data_prod:
